development:
  cloud_name: academy
  api_key: '378846794624657'
  api_secret: qhBT83C6SsTRo0ejhSKwsMu0nFE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: academy
  api_key: '378846794624657'
  api_secret: qhBT83C6SsTRo0ejhSKwsMu0nFE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: academy
  api_key: '378846794624657'
  api_secret: qhBT83C6SsTRo0ejhSKwsMu0nFE
  enhance_image_tag: true
  static_image_support: false
